apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: es-cluster
spec:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.3
    image-pull-policy: Always
  cerebro:
    image: upmcenterprises/cerebro:0.7.2
    image-pull-policy: Always
  elastic-search-image: fico-dmp-docker-development.jfrog.io/fico/dmp-service-test:elasticsearch-mod-v0.1
  elasticsearchEnv:
    - name: PUBLIC_KEY
      value: "default"
    - name: NETWORK_HOST
      value: "_eth0:ipv4_"
  image-pull-secrets:
    - name: dmpregistrykey
  image-pull-policy: Always
  client-node-replicas: 1
  master-node-replicas: 1
  data-node-replicas: 1
  network-host: 0.0.0.0
  zones: []
  data-volume-size: 1Gi
  java-options: "-Xms512m -Xmx512m"
  snapshot:
    scheduler-enabled: false
    bucket-name: nosql-provider
    cron-schedule: "@every 1m"
    image: upmcenterprises/elasticsearch-cron:0.0.4
  storage:
    type: standard
    storage-class-provisioner: volume.alpha.kubernetes.io/storage-class
    volume-reclaim-policy: Delete
